// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
  properties: {
    grant_type: {
      anyOf: [
        {
          type: "string",
          pattern: "^password$",
        },
        {
          type: "null",
        },
      ],
      title: "Grant Type",
    },
    username: {
      type: "string",
      title: "Username",
    },
    password: {
      type: "string",
      format: "password",
      title: "Password",
    },
    scope: {
      type: "string",
      title: "Scope",
      default: "",
    },
    client_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Client Id",
    },
    client_secret: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      format: "password",
      title: "Client Secret",
    },
  },
  type: "object",
  required: ["username", "password"],
  title: "Body_login-login_access_token",
} as const;

export const CashierCreateSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    inn: {
      type: "string",
      title: "Inn",
    },
  },
  type: "object",
  required: ["name", "inn"],
  title: "CashierCreate",
} as const;

export const CashierPublicSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    inn: {
      type: "string",
      title: "Inn",
    },
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
  },
  type: "object",
  required: ["name", "inn", "id"],
  title: "CashierPublic",
} as const;

export const CashierUpdateSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    inn: {
      type: "string",
      title: "Inn",
    },
  },
  type: "object",
  required: ["name", "inn"],
  title: "CashierUpdate",
} as const;

export const CashiersPublicSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/CashierPublic",
      },
      type: "array",
      title: "Data",
    },
    count: {
      type: "integer",
      title: "Count",
    },
  },
  type: "object",
  required: ["data", "count"],
  title: "CashiersPublic",
  description: "Paginated list of public cashiers.",
} as const;

export const ShopOwnerCreateSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    inn: {
      type: "string",
      title: "Inn",
    },
  },
  type: "object",
  required: ["name", "inn"],
  title: "ShopOwnerCreate",
} as const;

export const ShopOwnerPublicSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    inn: {
      type: "string",
      title: "Inn",
    },
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
  },
  type: "object",
  required: ["name", "inn", "id"],
  title: "ShopOwnerPublic",
} as const;

export const ShopOwnerUpdateSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    inn: {
      type: "string",
      title: "Inn",
    },
  },
  type: "object",
  required: ["name", "inn"],
  title: "ShopOwnerUpdate",
} as const;

export const ShopOwnersPublicSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/ShopOwnerPublic",
      },
      type: "array",
      title: "Data",
    },
    count: {
      type: "integer",
      title: "Count",
    },
  },
  type: "object",
  required: ["data", "count"],
  title: "ShopOwnersPublic",
  description: "Paginated list of public shop owners.",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const HealthCheckSchema = {
  properties: {
    app: {
      type: "boolean",
      title: "App",
    },
    database: {
      type: "boolean",
      title: "Database",
    },
  },
  type: "object",
  required: ["app", "database"],
  title: "HealthCheck",
  description: "Health check response.",
} as const;

export const ItemCreateSchema = {
  properties: {
    title: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Title",
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
  },
  type: "object",
  required: ["title"],
  title: "ItemCreate",
  description: "Item creation payload.",
} as const;

export const ItemPublicSchema = {
  properties: {
    title: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Title",
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    owner_id: {
      type: "string",
      format: "uuid",
      title: "Owner Id",
    },
    created_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Created At",
    },
  },
  type: "object",
  required: ["title", "id", "owner_id"],
  title: "ItemPublic",
  description: "Public item representation.",
} as const;

export const ItemUpdateSchema = {
  properties: {
    title: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Title",
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
  },
  type: "object",
  title: "ItemUpdate",
  description: "Item update payload (fields optional).",
} as const;

export const ItemsPublicSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/ItemPublic",
      },
      type: "array",
      title: "Data",
    },
    count: {
      type: "integer",
      title: "Count",
    },
  },
  type: "object",
  required: ["data", "count"],
  title: "ItemsPublic",
  description: "Paginated list of public items.",
} as const;

export const MessageSchema = {
  properties: {
    message: {
      type: "string",
      title: "Message",
    },
  },
  type: "object",
  required: ["message"],
  title: "Message",
  description: "Generic message response.",
} as const;

export const NewPasswordSchema = {
  properties: {
    token: {
      type: "string",
      title: "Token",
    },
    new_password: {
      type: "string",
      maxLength: 128,
      minLength: 8,
      title: "New Password",
    },
  },
  type: "object",
  required: ["token", "new_password"],
  title: "NewPassword",
  description: "Password reset payload.",
} as const;

export const PrivateUserCreateSchema = {
  properties: {
    email: {
      type: "string",
      title: "Email",
    },
    password: {
      type: "string",
      title: "Password",
    },
    full_name: {
      type: "string",
      title: "Full Name",
    },
    is_verified: {
      type: "boolean",
      title: "Is Verified",
      default: false,
    },
  },
  type: "object",
  required: ["email", "password", "full_name"],
  title: "PrivateUserCreate",
} as const;

export const SetShopCategoriesSchema = {
  properties: {
    category_ids: {
      items: {
        type: "string",
        format: "uuid",
      },
      type: "array",
      title: "Category Ids",
    },
  },
  type: "object",
  title: "SetShopCategories",
} as const;

export const ShopCategoryCreateSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
  },
  type: "object",
  required: ["name"],
  title: "ShopCategoryCreate",
} as const;

export const ShopCategoryPublicSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
    },
  },
  type: "object",
  required: ["id", "name", "is_active"],
  title: "ShopCategoryPublic",
} as const;

export const ShopCategoryUpdateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    is_active: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Is Active",
    },
  },
  type: "object",
  title: "ShopCategoryUpdate",
} as const;

export const ShopCategorysPublicSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/ShopCategoryPublic",
      },
      type: "array",
      title: "Data",
    },
    count: {
      type: "integer",
      title: "Count",
    },
  },
  type: "object",
  required: ["data", "count"],
  title: "ShopCategorysPublic",
  description: "Paginated list of public shops categorys.",
} as const;

export const ShopCreateSchema = {
  properties: {
    retail_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Retail Name",
    },
    address: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Address",
    },
    is_favorite: {
      type: "boolean",
      title: "Is Favorite",
      default: false,
    },
    notes: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Notes",
    },
    shop_owner_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Shop Owner Id",
    },
  },
  type: "object",
  title: "ShopCreate",
} as const;

export const ShopPublicSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    retail_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Retail Name",
    },
    address: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Address",
    },
    is_favorite: {
      type: "boolean",
      title: "Is Favorite",
    },
    notes: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Notes",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
    },
    shop_owner_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Shop Owner Id",
    },
    category_ids: {
      items: {
        type: "string",
        format: "uuid",
      },
      type: "array",
      title: "Category Ids",
    },
  },
  type: "object",
  required: [
    "id",
    "retail_name",
    "address",
    "is_favorite",
    "notes",
    "is_active",
  ],
  title: "ShopPublic",
} as const;

export const ShopReadSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    retail_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Retail Name",
    },
    address: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Address",
    },
    is_favorite: {
      type: "boolean",
      title: "Is Favorite",
    },
    notes: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Notes",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
    },
    shop_owner_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Shop Owner Id",
    },
  },
  type: "object",
  required: [
    "id",
    "retail_name",
    "address",
    "is_favorite",
    "notes",
    "is_active",
  ],
  title: "ShopRead",
} as const;

export const ShopUpdateSchema = {
  properties: {
    retail_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Retail Name",
    },
    address: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Address",
    },
    is_favorite: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Is Favorite",
    },
    notes: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Notes",
    },
    is_active: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Is Active",
    },
    shop_owner_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Shop Owner Id",
    },
  },
  type: "object",
  title: "ShopUpdate",
} as const;

export const ShopsPublicSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/ShopRead",
      },
      type: "array",
      title: "Data",
    },
    count: {
      type: "integer",
      title: "Count",
    },
  },
  type: "object",
  required: ["data", "count"],
  title: "ShopsPublic",
  description: "Paginated list of public shops.",
} as const;

export const TokenSchema = {
  properties: {
    access_token: {
      type: "string",
      title: "Access Token",
    },
    token_type: {
      type: "string",
      title: "Token Type",
      default: "bearer",
    },
  },
  type: "object",
  required: ["access_token"],
  title: "Token",
  description: "Access token payload.",
} as const;

export const UpdatePasswordSchema = {
  properties: {
    current_password: {
      type: "string",
      maxLength: 128,
      minLength: 8,
      title: "Current Password",
    },
    new_password: {
      type: "string",
      maxLength: 128,
      minLength: 8,
      title: "New Password",
    },
  },
  type: "object",
  required: ["current_password", "new_password"],
  title: "UpdatePassword",
  description: "Password change payload.",
} as const;

export const UserCreateSchema = {
  properties: {
    email: {
      type: "string",
      maxLength: 255,
      format: "email",
      title: "Email",
    },
    telegram_id: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Telegram Id",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      default: true,
    },
    is_superuser: {
      type: "boolean",
      title: "Is Superuser",
      default: false,
    },
    full_name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
    password: {
      type: "string",
      maxLength: 128,
      minLength: 8,
      title: "Password",
    },
  },
  type: "object",
  required: ["email", "password"],
  title: "UserCreate",
  description: "User creation payload with password.",
} as const;

export const UserPublicSchema = {
  properties: {
    email: {
      type: "string",
      maxLength: 255,
      format: "email",
      title: "Email",
    },
    telegram_id: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Telegram Id",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      default: true,
    },
    is_superuser: {
      type: "boolean",
      title: "Is Superuser",
      default: false,
    },
    full_name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    created_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Created At",
    },
  },
  type: "object",
  required: ["email", "id"],
  title: "UserPublic",
  description: "Public user representation.",
} as const;

export const UserRegisterSchema = {
  properties: {
    email: {
      type: "string",
      maxLength: 255,
      format: "email",
      title: "Email",
    },
    password: {
      type: "string",
      maxLength: 128,
      minLength: 8,
      title: "Password",
    },
    full_name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
  },
  type: "object",
  required: ["email", "password"],
  title: "UserRegister",
  description: "User self-registration payload.",
} as const;

export const UserUpdateSchema = {
  properties: {
    email: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
          format: "email",
        },
        {
          type: "null",
        },
      ],
      title: "Email",
    },
    telegram_id: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Telegram Id",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      default: true,
    },
    is_superuser: {
      type: "boolean",
      title: "Is Superuser",
      default: false,
    },
    full_name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
    password: {
      anyOf: [
        {
          type: "string",
          maxLength: 128,
          minLength: 8,
        },
        {
          type: "null",
        },
      ],
      title: "Password",
    },
  },
  type: "object",
  title: "UserUpdate",
  description: "User update payload (all fields optional).",
} as const;

export const UserUpdateMeSchema = {
  properties: {
    full_name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
    telegram_id: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Telegram Id",
    },
    email: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
          format: "email",
        },
        {
          type: "null",
        },
      ],
      title: "Email",
    },
  },
  type: "object",
  title: "UserUpdateMe",
  description: "User self-update payload.",
} as const;

export const UsersPublicSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/UserPublic",
      },
      type: "array",
      title: "Data",
    },
    count: {
      type: "integer",
      title: "Count",
    },
  },
  type: "object",
  required: ["data", "count"],
  title: "UsersPublic",
  description: "Paginated list of public users.",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
