// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_login_access_token'
} as const;

export const Body_receipts_create_receipt_from_raw_fileSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_receipts_create_receipt_from_raw_file'
} as const;

export const Body_receipts_import_receiptsSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_receipts_import_receipts'
} as const;

export const CashierCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        inn: {
            type: 'string',
            title: 'Inn'
        }
    },
    type: 'object',
    required: ['name', 'inn'],
    title: 'CashierCreate'
} as const;

export const CashierPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        inn: {
            type: 'string',
            title: 'Inn'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'inn', 'id'],
    title: 'CashierPublic'
} as const;

export const CashierUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        inn: {
            type: 'string',
            title: 'Inn'
        }
    },
    type: 'object',
    required: ['name', 'inn'],
    title: 'CashierUpdate'
} as const;

export const CashiersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CashierPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CashiersPublic',
    description: 'Paginated list of public cashiers.'
} as const;

export const DashboardPaymentSplitSchema = {
    properties: {
        cash_total_sum: {
            type: 'integer',
            title: 'Cash Total Sum'
        },
        ecash_total_sum: {
            type: 'integer',
            title: 'Ecash Total Sum'
        },
        total_sum: {
            type: 'integer',
            title: 'Total Sum'
        },
        cash_percent: {
            type: 'number',
            title: 'Cash Percent'
        },
        ecash_percent: {
            type: 'number',
            title: 'Ecash Percent'
        }
    },
    type: 'object',
    required: ['cash_total_sum', 'ecash_total_sum', 'total_sum', 'cash_percent', 'ecash_percent'],
    title: 'DashboardPaymentSplit'
} as const;

export const DashboardResponseSchema = {
    properties: {
        totals: {
            '$ref': '#/components/schemas/DashboardTotals'
        },
        payment_split: {
            '$ref': '#/components/schemas/DashboardPaymentSplit'
        },
        timeseries: {
            items: {
                '$ref': '#/components/schemas/DashboardTimeseriesPoint'
            },
            type: 'array',
            title: 'Timeseries'
        },
        top_shops: {
            items: {
                '$ref': '#/components/schemas/DashboardTopShop'
            },
            type: 'array',
            title: 'Top Shops'
        },
        latest_receipts: {
            '$ref': '#/components/schemas/ReceiptsShortPublic'
        }
    },
    type: 'object',
    required: ['totals', 'payment_split', 'timeseries', 'top_shops', 'latest_receipts'],
    title: 'DashboardResponse'
} as const;

export const DashboardTimeseriesPointSchema = {
    properties: {
        date: {
            type: 'string',
            title: 'Date'
        },
        revenue: {
            type: 'integer',
            title: 'Revenue'
        },
        receipts_count: {
            type: 'integer',
            title: 'Receipts Count'
        },
        avg_receipt: {
            type: 'number',
            title: 'Avg Receipt'
        }
    },
    type: 'object',
    required: ['date', 'revenue', 'receipts_count', 'avg_receipt'],
    title: 'DashboardTimeseriesPoint'
} as const;

export const DashboardTopShopSchema = {
    properties: {
        shop_id: {
            type: 'string',
            format: 'uuid',
            title: 'Shop Id'
        },
        shop_display: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Display'
        },
        shop_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Name'
        },
        shop_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Address'
        },
        total_sum: {
            type: 'integer',
            title: 'Total Sum'
        },
        receipts_count: {
            type: 'integer',
            title: 'Receipts Count'
        }
    },
    type: 'object',
    required: ['shop_id', 'total_sum', 'receipts_count'],
    title: 'DashboardTopShop'
} as const;

export const DashboardTotalsSchema = {
    properties: {
        revenue: {
            type: 'integer',
            title: 'Revenue'
        },
        receipts_count: {
            type: 'integer',
            title: 'Receipts Count'
        },
        avg_receipt: {
            type: 'number',
            title: 'Avg Receipt'
        },
        unique_shops: {
            type: 'integer',
            title: 'Unique Shops'
        }
    },
    type: 'object',
    required: ['revenue', 'receipts_count', 'avg_receipt', 'unique_shops'],
    title: 'DashboardTotals'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthCheckSchema = {
    properties: {
        app: {
            type: 'boolean',
            title: 'App'
        },
        database: {
            type: 'boolean',
            title: 'Database'
        }
    },
    type: 'object',
    required: ['app', 'database'],
    title: 'HealthCheck',
    description: 'Health check response.'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate',
    description: 'Item creation payload.'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic',
    description: 'Public item representation.'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate',
    description: 'Item update payload (fields optional).'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic',
    description: 'Paginated list of public items.'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: 'Generic message response.'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword',
    description: 'Password reset payload.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ReceiptImportErrorSchema = {
    properties: {
        line: {
            type: 'integer',
            title: 'Line'
        },
        detail: {
            type: 'string',
            title: 'Detail'
        }
    },
    type: 'object',
    required: ['line', 'detail'],
    title: 'ReceiptImportError'
} as const;

export const ReceiptImportSummarySchema = {
    properties: {
        imported: {
            type: 'integer',
            title: 'Imported'
        },
        skipped: {
            type: 'integer',
            title: 'Skipped'
        },
        failed: {
            type: 'integer',
            title: 'Failed'
        },
        errors: {
            items: {
                '$ref': '#/components/schemas/ReceiptImportError'
            },
            type: 'array',
            title: 'Errors'
        }
    },
    type: 'object',
    required: ['imported', 'skipped', 'failed'],
    title: 'ReceiptImportSummary'
} as const;

export const ReceiptItemCategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ReceiptItemCategoryCreate'
} as const;

export const ReceiptItemCategoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['id', 'name', 'is_active'],
    title: 'ReceiptItemCategoryPublic'
} as const;

export const ReceiptItemCategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'ReceiptItemCategoryUpdate'
} as const;

export const ReceiptItemCategorysPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ReceiptItemCategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ReceiptItemCategorysPublic'
} as const;

export const ReceiptItemCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 500,
            title: 'Name'
        },
        price: {
            type: 'integer',
            title: 'Price'
        },
        quantity: {
            type: 'number',
            title: 'Quantity'
        },
        sum: {
            type: 'integer',
            title: 'Sum'
        },
        measure: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Measure',
            default: 'шт'
        },
        product_type: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Type'
        },
        gtin: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gtin'
        },
        raw_product_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Product Code'
        },
        receipt_id: {
            type: 'string',
            format: 'uuid',
            title: 'Receipt Id'
        }
    },
    type: 'object',
    required: ['name', 'price', 'quantity', 'sum', 'receipt_id'],
    title: 'ReceiptItemCreate'
} as const;

export const ReceiptItemGroupPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        quantity: {
            type: 'number',
            title: 'Quantity'
        },
        sum: {
            type: 'integer',
            title: 'Sum'
        },
        items_count: {
            type: 'integer',
            title: 'Items Count'
        }
    },
    type: 'object',
    required: ['name', 'quantity', 'sum', 'items_count'],
    title: 'ReceiptItemGroupPublic'
} as const;

export const ReceiptItemGroupsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ReceiptItemGroupPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ReceiptItemGroupsPublic'
} as const;

export const ReceiptItemInlineCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 500,
            title: 'Name'
        },
        price: {
            type: 'integer',
            title: 'Price'
        },
        quantity: {
            type: 'number',
            title: 'Quantity'
        },
        sum: {
            type: 'integer',
            title: 'Sum'
        },
        measure: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Measure',
            default: 'шт'
        },
        product_type: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Type'
        },
        gtin: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gtin'
        },
        raw_product_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Product Code'
        }
    },
    type: 'object',
    required: ['name', 'price', 'quantity', 'sum'],
    title: 'ReceiptItemInlineCreate',
    description: 'Receipt item payload for nested receipt creation.'
} as const;

export const ReceiptItemPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 500,
            title: 'Name'
        },
        price: {
            type: 'integer',
            title: 'Price'
        },
        quantity: {
            type: 'number',
            title: 'Quantity'
        },
        sum: {
            type: 'integer',
            title: 'Sum'
        },
        measure: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Measure',
            default: 'шт'
        },
        product_type: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Type'
        },
        gtin: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gtin'
        },
        raw_product_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Product Code'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        receipt_id: {
            type: 'string',
            format: 'uuid',
            title: 'Receipt Id'
        },
        category_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Category Ids'
        }
    },
    type: 'object',
    required: ['name', 'price', 'quantity', 'sum', 'id', 'receipt_id'],
    title: 'ReceiptItemPublic'
} as const;

export const ReceiptItemReadSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 500,
            title: 'Name'
        },
        price: {
            type: 'integer',
            title: 'Price'
        },
        quantity: {
            type: 'number',
            title: 'Quantity'
        },
        sum: {
            type: 'integer',
            title: 'Sum'
        },
        measure: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Measure',
            default: 'шт'
        },
        product_type: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Type'
        },
        gtin: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gtin'
        },
        raw_product_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Product Code'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        receipt_id: {
            type: 'string',
            format: 'uuid',
            title: 'Receipt Id'
        }
    },
    type: 'object',
    required: ['name', 'price', 'quantity', 'sum', 'id', 'receipt_id'],
    title: 'ReceiptItemRead'
} as const;

export const ReceiptItemUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        price: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        quantity: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quantity'
        },
        sum: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sum'
        },
        measure: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Measure'
        },
        product_type: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Type'
        },
        gtin: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gtin'
        },
        raw_product_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Product Code'
        },
        receipt_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Receipt Id'
        }
    },
    type: 'object',
    title: 'ReceiptItemUpdate'
} as const;

export const ReceiptReadSchema = {
    properties: {
        date_time: {
            type: 'string',
            format: 'date-time',
            title: 'Date Time'
        },
        code: {
            type: 'integer',
            title: 'Code'
        },
        cash_total_sum: {
            type: 'integer',
            title: 'Cash Total Sum'
        },
        credit_sum: {
            type: 'integer',
            title: 'Credit Sum'
        },
        ecash_total_sum: {
            type: 'integer',
            title: 'Ecash Total Sum'
        },
        total_sum: {
            type: 'integer',
            title: 'Total Sum'
        },
        prepaid_sum: {
            type: 'integer',
            title: 'Prepaid Sum'
        },
        provision_sum: {
            type: 'integer',
            title: 'Provision Sum'
        },
        fiscal_document_format_ver: {
            type: 'integer',
            title: 'Fiscal Document Format Ver'
        },
        fiscal_drive_number: {
            type: 'string',
            maxLength: 20,
            title: 'Fiscal Drive Number'
        },
        fiscal_document_number: {
            type: 'integer',
            title: 'Fiscal Document Number'
        },
        fiscal_sign: {
            type: 'integer',
            title: 'Fiscal Sign'
        },
        shift_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shift Number'
        },
        kkt_reg_id: {
            type: 'string',
            maxLength: 20,
            title: 'Kkt Reg Id'
        },
        nds_10: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nds 10'
        },
        nds_18: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nds 18'
        },
        operation_type: {
            type: 'integer',
            title: 'Operation Type'
        },
        request_number: {
            type: 'integer',
            title: 'Request Number'
        },
        taxation_type: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Taxation Type'
        },
        applied_taxation_type: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Applied Taxation Type'
        },
        shop_id: {
            type: 'string',
            format: 'uuid',
            title: 'Shop Id'
        },
        cashier_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cashier Id'
        },
        status: {
            '$ref': '#/components/schemas/ReceiptStatus',
            default: 'draft'
        },
        source: {
            '$ref': '#/components/schemas/ReceiptSource',
            default: 'manual'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['date_time', 'code', 'cash_total_sum', 'credit_sum', 'ecash_total_sum', 'total_sum', 'prepaid_sum', 'provision_sum', 'fiscal_document_format_ver', 'fiscal_drive_number', 'fiscal_document_number', 'fiscal_sign', 'kkt_reg_id', 'operation_type', 'request_number', 'shop_id', 'id', 'owner_id'],
    title: 'ReceiptRead'
} as const;

export const ReceiptShopUpdateSchema = {
    properties: {
        shop_id: {
            type: 'string',
            format: 'uuid',
            title: 'Shop Id'
        }
    },
    type: 'object',
    required: ['shop_id'],
    title: 'ReceiptShopUpdate'
} as const;

export const ReceiptShortSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        date_time: {
            type: 'string',
            format: 'date-time',
            title: 'Date Time'
        },
        total_sum: {
            type: 'integer',
            title: 'Total Sum'
        },
        cash_total_sum: {
            type: 'integer',
            title: 'Cash Total Sum'
        },
        ecash_total_sum: {
            type: 'integer',
            title: 'Ecash Total Sum'
        },
        items_count: {
            type: 'integer',
            title: 'Items Count'
        },
        shop_display: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Display'
        },
        shop: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ShopRead'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'date_time', 'total_sum', 'cash_total_sum', 'ecash_total_sum', 'items_count'],
    title: 'ReceiptShort'
} as const;

export const ReceiptSourceSchema = {
    type: 'string',
    enum: ['manual', 'fns_import', 'external_import'],
    title: 'ReceiptSource'
} as const;

export const ReceiptStatusSchema = {
    type: 'string',
    enum: ['draft', 'finalized', 'archived'],
    title: 'ReceiptStatus'
} as const;

export const ReceiptWithItemsFullPublicSchema = {
    properties: {
        receipt: {
            '$ref': '#/components/schemas/ReceiptRead'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/ReceiptItemRead'
            },
            type: 'array',
            title: 'Items'
        },
        shop: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ShopRead'
                },
                {
                    type: 'null'
                }
            ]
        },
        shop_owner: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ShopOwnerPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        cashier: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CashierPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['receipt', 'items'],
    title: 'ReceiptWithItemsFullPublic',
    description: 'Full representation of a receipt with nested items and related entities.'
} as const;

export const ReceiptWithItemsPublicSchema = {
    properties: {
        receipt: {
            '$ref': '#/components/schemas/ReceiptRead'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/ReceiptItemRead'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['receipt', 'items'],
    title: 'ReceiptWithItemsPublic',
    description: 'Public representation of a receipt with nested items.'
} as const;

export const ReceiptsShortPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ReceiptShort'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ReceiptsShortPublic'
} as const;

export const SetReceiptItemCategoriesSchema = {
    properties: {
        category_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Category Ids'
        }
    },
    type: 'object',
    title: 'SetReceiptItemCategories'
} as const;

export const SetReceiptItemsCategoriesByNameSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Name'
        },
        category_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Category Ids'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'SetReceiptItemsCategoriesByName'
} as const;

export const SetShopCategoriesSchema = {
    properties: {
        category_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Category Ids'
        }
    },
    type: 'object',
    title: 'SetShopCategories'
} as const;

export const ShopAddressPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        address_raw: {
            type: 'string',
            title: 'Address Raw'
        },
        address_normalized: {
            type: 'string',
            title: 'Address Normalized'
        },
        first_seen_at: {
            type: 'string',
            format: 'date-time',
            title: 'First Seen At'
        },
        last_seen_at: {
            type: 'string',
            format: 'date-time',
            title: 'Last Seen At'
        },
        seen_count: {
            type: 'integer',
            title: 'Seen Count'
        },
        is_primary: {
            type: 'boolean',
            title: 'Is Primary'
        }
    },
    type: 'object',
    required: ['id', 'address_raw', 'address_normalized', 'first_seen_at', 'last_seen_at', 'seen_count', 'is_primary'],
    title: 'ShopAddressPublic'
} as const;

export const ShopCategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ShopCategoryCreate'
} as const;

export const ShopCategoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['id', 'name', 'is_active'],
    title: 'ShopCategoryPublic'
} as const;

export const ShopCategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'ShopCategoryUpdate'
} as const;

export const ShopCategorysPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ShopCategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ShopCategorysPublic',
    description: 'Paginated list of public shops categorys.'
} as const;

export const ShopCreateSchema = {
    properties: {
        retail_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Retail Name'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        is_favorite: {
            type: 'boolean',
            title: 'Is Favorite',
            default: false
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        shop_owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Owner Id'
        }
    },
    type: 'object',
    title: 'ShopCreate'
} as const;

export const ShopOwnerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        inn: {
            type: 'string',
            title: 'Inn'
        }
    },
    type: 'object',
    required: ['name', 'inn'],
    title: 'ShopOwnerCreate'
} as const;

export const ShopOwnerNamePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name_raw: {
            type: 'string',
            title: 'Name Raw'
        },
        name_normalized: {
            type: 'string',
            title: 'Name Normalized'
        },
        first_seen_at: {
            type: 'string',
            format: 'date-time',
            title: 'First Seen At'
        },
        last_seen_at: {
            type: 'string',
            format: 'date-time',
            title: 'Last Seen At'
        },
        seen_count: {
            type: 'integer',
            title: 'Seen Count'
        },
        is_primary: {
            type: 'boolean',
            title: 'Is Primary'
        }
    },
    type: 'object',
    required: ['id', 'name_raw', 'name_normalized', 'first_seen_at', 'last_seen_at', 'seen_count', 'is_primary'],
    title: 'ShopOwnerNamePublic'
} as const;

export const ShopOwnerPrimaryAliasUpdateSchema = {
    properties: {
        alias_id: {
            type: 'string',
            format: 'uuid',
            title: 'Alias Id'
        }
    },
    type: 'object',
    required: ['alias_id'],
    title: 'ShopOwnerPrimaryAliasUpdate'
} as const;

export const ShopOwnerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        inn: {
            type: 'string',
            title: 'Inn'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        aliases_count: {
            type: 'integer',
            title: 'Aliases Count',
            default: 0
        },
        has_name_conflict: {
            type: 'boolean',
            title: 'Has Name Conflict',
            default: false
        },
        aliases: {
            items: {
                '$ref': '#/components/schemas/ShopOwnerNamePublic'
            },
            type: 'array',
            title: 'Aliases'
        }
    },
    type: 'object',
    required: ['name', 'inn', 'id'],
    title: 'ShopOwnerPublic'
} as const;

export const ShopOwnerUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        inn: {
            type: 'string',
            title: 'Inn'
        }
    },
    type: 'object',
    required: ['name', 'inn'],
    title: 'ShopOwnerUpdate'
} as const;

export const ShopOwnersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ShopOwnerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ShopOwnersPublic',
    description: 'Paginated list of public shop owners.'
} as const;

export const ShopPrimaryAddressUpdateSchema = {
    properties: {
        alias_id: {
            type: 'string',
            format: 'uuid',
            title: 'Alias Id'
        }
    },
    type: 'object',
    required: ['alias_id'],
    title: 'ShopPrimaryAddressUpdate'
} as const;

export const ShopPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        retail_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Retail Name'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        is_favorite: {
            type: 'boolean',
            title: 'Is Favorite'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        shop_owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Owner Id'
        },
        shop_owner: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ShopOwnerPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        category_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Category Ids'
        },
        address_aliases_count: {
            type: 'integer',
            title: 'Address Aliases Count',
            default: 0
        },
        has_address_conflict: {
            type: 'boolean',
            title: 'Has Address Conflict',
            default: false
        },
        addresses: {
            items: {
                '$ref': '#/components/schemas/ShopAddressPublic'
            },
            type: 'array',
            title: 'Addresses'
        }
    },
    type: 'object',
    required: ['id', 'retail_name', 'address', 'is_favorite', 'notes', 'is_active', 'shop_owner_id'],
    title: 'ShopPublic'
} as const;

export const ShopReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        retail_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Retail Name'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        is_favorite: {
            type: 'boolean',
            title: 'Is Favorite'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        shop_owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Owner Id'
        },
        shop_owner: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ShopOwnerPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        category_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Category Ids'
        },
        address_aliases_count: {
            type: 'integer',
            title: 'Address Aliases Count',
            default: 0
        },
        has_address_conflict: {
            type: 'boolean',
            title: 'Has Address Conflict',
            default: false
        },
        addresses: {
            items: {
                '$ref': '#/components/schemas/ShopAddressPublic'
            },
            type: 'array',
            title: 'Addresses'
        }
    },
    type: 'object',
    required: ['id', 'retail_name', 'address', 'is_favorite', 'notes', 'is_active', 'shop_owner_id'],
    title: 'ShopRead'
} as const;

export const ShopUpdateSchema = {
    properties: {
        retail_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Retail Name'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        is_favorite: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Favorite'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        shop_owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Shop Owner Id'
        }
    },
    type: 'object',
    title: 'ShopUpdate'
} as const;

export const ShopsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ShopRead'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ShopsPublic',
    description: 'Paginated list of public shops.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token',
    description: 'Access token payload.'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword',
    description: 'Password change payload.'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        telegram_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate',
    description: 'User creation payload with password.'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        telegram_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic',
    description: 'Public user representation.'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: 'User self-registration payload.'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        telegram_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: 'User update payload (all fields optional).'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        telegram_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Id'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: 'User self-update payload.'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic',
    description: 'Paginated list of public users.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;