// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type CashierCreate = {
  name: string;
  inn: string;
};

export type CashierPublic = {
  name: string;
  inn: string;
  id: string;
};

/**
 * Paginated list of public cashiers.
 */
export type CashiersPublic = {
  data: Array<CashierPublic>;
  count: number;
};

export type CashierUpdate = {
  name: string;
  inn: string;
};

export type ShopOwnerCreate = {
  name: string;
  inn: string;
};

export type ShopOwnerPublic = {
  name: string;
  inn: string;
  id: string;
};

/**
 * Paginated list of public shop owners.
 */
export type ShopOwnersPublic = {
  data: Array<ShopOwnerPublic>;
  count: number;
};

export type ShopOwnerUpdate = {
  name: string;
  inn: string;
};

/**
 * Health check response.
 */
export type HealthCheck = {
  app: boolean;
  database: boolean;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

/**
 * Item creation payload.
 */
export type ItemCreate = {
  title: string;
  description?: string | null;
};

/**
 * Public item representation.
 */
export type ItemPublic = {
  title: string;
  description?: string | null;
  id: string;
  owner_id: string;
  created_at?: string | null;
};

/**
 * Paginated list of public items.
 */
export type ItemsPublic = {
  data: Array<ItemPublic>;
  count: number;
};

/**
 * Item update payload (fields optional).
 */
export type ItemUpdate = {
  title?: string | null;
  description?: string | null;
};

/**
 * Generic message response.
 */
export type Message = {
  message: string;
};

/**
 * Password reset payload.
 */
export type NewPassword = {
  token: string;
  new_password: string;
};

export type PrivateUserCreate = {
  email: string;
  password: string;
  full_name: string;
  is_verified?: boolean;
};

export type SetShopCategories = {
  category_ids?: Array<string>;
};

export type ShopCategoryCreate = {
  name: string;
};

export type ShopCategoryPublic = {
  id: string;
  name: string;
  is_active: boolean;
};

/**
 * Paginated list of public shops categorys.
 */
export type ShopCategorysPublic = {
  data: Array<ShopCategoryPublic>;
  count: number;
};

export type ShopCategoryUpdate = {
  name?: string | null;
  is_active?: boolean | null;
};

export type ShopCreate = {
  retail_name?: string | null;
  address?: string | null;
  is_favorite?: boolean;
  notes?: string | null;
  shop_owner_id?: string | null;
};

export type ShopPublic = {
  id: string;
  retail_name: string | null;
  address: string | null;
  is_favorite: boolean;
  notes: string | null;
  is_active: boolean;
  shop_owner_id?: string | null;
  category_ids?: Array<string>;
};

export type ShopRead = {
  id: string;
  retail_name: string | null;
  address: string | null;
  is_favorite: boolean;
  notes: string | null;
  is_active: boolean;
  shop_owner_id?: string | null;
};

/**
 * Paginated list of public shops.
 */
export type ShopsPublic = {
  data: Array<ShopRead>;
  count: number;
};

export type ShopUpdate = {
  retail_name?: string | null;
  address?: string | null;
  is_favorite?: boolean | null;
  notes?: string | null;
  is_active?: boolean | null;
  shop_owner_id?: string | null;
};

/**
 * Access token payload.
 */
export type Token = {
  access_token: string;
  token_type?: string;
};

/**
 * Password change payload.
 */
export type UpdatePassword = {
  current_password: string;
  new_password: string;
};

/**
 * User creation payload with password.
 */
export type UserCreate = {
  email: string;
  telegram_id?: string | null;
  is_active?: boolean;
  is_superuser?: boolean;
  full_name?: string | null;
  password: string;
};

/**
 * Public user representation.
 */
export type UserPublic = {
  email: string;
  telegram_id?: string | null;
  is_active?: boolean;
  is_superuser?: boolean;
  full_name?: string | null;
  id: string;
  created_at?: string | null;
};

/**
 * User self-registration payload.
 */
export type UserRegister = {
  email: string;
  password: string;
  full_name?: string | null;
};

/**
 * Paginated list of public users.
 */
export type UsersPublic = {
  data: Array<UserPublic>;
  count: number;
};

/**
 * User update payload (all fields optional).
 */
export type UserUpdate = {
  email?: string | null;
  telegram_id?: string | null;
  is_active?: boolean;
  is_superuser?: boolean;
  full_name?: string | null;
  password?: string | null;
};

/**
 * User self-update payload.
 */
export type UserUpdateMe = {
  full_name?: string | null;
  telegram_id?: string | null;
  email?: string | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type CashiersReadCashiersData = {
  limit?: number;
  skip?: number;
};

export type CashiersReadCashiersResponse = CashiersPublic;

export type CashiersCreateCashierData = {
  requestBody: CashierCreate;
};

export type CashiersCreateCashierResponse = CashierPublic;

export type CashiersReadCashierData = {
  id: string;
};

export type CashiersReadCashierResponse = CashierPublic;

export type CashiersUpdateCashierData = {
  id: string;
  requestBody: CashierUpdate;
};

export type CashiersUpdateCashierResponse = CashierPublic;

export type CashiersDeleteCashierData = {
  id: string;
};

export type CashiersDeleteCashierResponse = Message;

export type ShopOwnersReadShopOwnersData = {
  limit?: number;
  skip?: number;
};

export type ShopOwnersReadShopOwnersResponse = ShopOwnersPublic;

export type ShopOwnersCreateShopOwnerData = {
  requestBody: ShopOwnerCreate;
};

export type ShopOwnersCreateShopOwnerResponse = ShopOwnerPublic;

export type ShopOwnersReadShopOwnerData = {
  id: string;
};

export type ShopOwnersReadShopOwnerResponse = ShopOwnerPublic;

export type ShopOwnersUpdateShopOwnerData = {
  id: string;
  requestBody: ShopOwnerUpdate;
};

export type ShopOwnersUpdateShopOwnerResponse = ShopOwnerPublic;

export type ShopOwnersDeleteShopOwnerData = {
  id: string;
};

export type ShopOwnersDeleteShopOwnerResponse = Message;

export type ItemsReadItemsData = {
  limit?: number;
  skip?: number;
};

export type ItemsReadItemsResponse = ItemsPublic;

export type ItemsCreateItemData = {
  requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = ItemPublic;

export type ItemsReadItemData = {
  id: string;
};

export type ItemsReadItemResponse = ItemPublic;

export type ItemsUpdateItemData = {
  id: string;
  requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = ItemPublic;

export type ItemsDeleteItemData = {
  id: string;
};

export type ItemsDeleteItemResponse = Message;

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = Token;

export type LoginTestTokenResponse = UserPublic;

export type LoginRecoverPasswordData = {
  email: string;
};

export type LoginRecoverPasswordResponse = Message;

export type LoginResetPasswordData = {
  requestBody: NewPassword;
};

export type LoginResetPasswordResponse = Message;

export type LoginRecoverPasswordHtmlContentData = {
  email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = string;

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = UserPublic;

export type ShopCategoriesReadShopCategoriesData = {
  limit?: number;
  q?: string | null;
  skip?: number;
};

export type ShopCategoriesReadShopCategoriesResponse = ShopCategorysPublic;

export type ShopCategoriesCreateCategoryData = {
  requestBody: ShopCategoryCreate;
};

export type ShopCategoriesCreateCategoryResponse = ShopCategoryPublic;

export type ShopCategoriesReadShopCategorieData = {
  categoryId: string;
};

export type ShopCategoriesReadShopCategorieResponse = ShopCategoryPublic;

export type ShopCategoriesUpdateCategoryData = {
  categoryId: string;
  requestBody: ShopCategoryUpdate;
};

export type ShopCategoriesUpdateCategoryResponse = ShopCategoryPublic;

export type ShopCategoriesDeleteCategoryData = {
  categoryId: string;
};

export type ShopCategoriesDeleteCategoryResponse = ShopCategoryPublic;

export type ShopsReadShopsData = {
  limit?: number;
  skip?: number;
};

export type ShopsReadShopsResponse = ShopsPublic;

export type ShopsCreateShopData = {
  requestBody: ShopCreate;
};

export type ShopsCreateShopResponse = ShopPublic;

export type ShopsReadShopData = {
  id: string;
};

export type ShopsReadShopResponse = ShopPublic;

export type ShopsUpdateShopData = {
  id: string;
  requestBody: ShopUpdate;
};

export type ShopsUpdateShopResponse = ShopPublic;

export type ShopsDeleteShopData = {
  id: string;
};

export type ShopsDeleteShopResponse = Message;

export type ShopsReplaceShopCategoriesData = {
  id: string;
  requestBody: SetShopCategories;
};

export type ShopsReplaceShopCategoriesResponse = ShopPublic;

export type UsersReadUsersData = {
  limit?: number;
  skip?: number;
};

export type UsersReadUsersResponse = UsersPublic;

export type UsersCreateUserData = {
  requestBody: UserCreate;
};

export type UsersCreateUserResponse = UserPublic;

export type UsersReadUserMeResponse = UserPublic;

export type UsersDeleteUserMeResponse = Message;

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = UserPublic;

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = Message;

export type UsersRegisterUserData = {
  requestBody: UserRegister;
};

export type UsersRegisterUserResponse = UserPublic;

export type UsersReadUserByIdData = {
  userId: string;
};

export type UsersReadUserByIdResponse = UserPublic;

export type UsersUpdateUserData = {
  requestBody: UserUpdate;
  userId: string;
};

export type UsersUpdateUserResponse = UserPublic;

export type UsersDeleteUserData = {
  userId: string;
};

export type UsersDeleteUserResponse = Message;

export type UtilsTestEmailData = {
  emailTo: string;
};

export type UtilsTestEmailResponse = Message;

export type UtilsHealthCheckResponse = HealthCheck;
