/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutShopsRouteImport } from './routes/_layout/shops'
import { Route as LayoutShopCategoriesRouteImport } from './routes/_layout/shop-categories'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRightsholdersRouteImport } from './routes/_layout/rightsholders'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutCashiersRouteImport } from './routes/_layout/cashiers'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShopsRoute = LayoutShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShopCategoriesRoute = LayoutShopCategoriesRouteImport.update({
  id: '/shop-categories',
  path: '/shop-categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRightsholdersRoute = LayoutRightsholdersRouteImport.update({
  id: '/rightsholders',
  path: '/rightsholders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCashiersRoute = LayoutCashiersRouteImport.update({
  id: '/cashiers',
  path: '/cashiers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/cashiers': typeof LayoutCashiersRoute
  '/items': typeof LayoutItemsRoute
  '/rightsholders': typeof LayoutRightsholdersRoute
  '/settings': typeof LayoutSettingsRoute
  '/shop-categories': typeof LayoutShopCategoriesRoute
  '/shops': typeof LayoutShopsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/cashiers': typeof LayoutCashiersRoute
  '/items': typeof LayoutItemsRoute
  '/rightsholders': typeof LayoutRightsholdersRoute
  '/settings': typeof LayoutSettingsRoute
  '/shop-categories': typeof LayoutShopCategoriesRoute
  '/shops': typeof LayoutShopsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/cashiers': typeof LayoutCashiersRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/rightsholders': typeof LayoutRightsholdersRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/shop-categories': typeof LayoutShopCategoriesRoute
  '/_layout/shops': typeof LayoutShopsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/cashiers'
    | '/items'
    | '/rightsholders'
    | '/settings'
    | '/shop-categories'
    | '/shops'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/cashiers'
    | '/items'
    | '/rightsholders'
    | '/settings'
    | '/shop-categories'
    | '/shops'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/cashiers'
    | '/_layout/items'
    | '/_layout/rightsholders'
    | '/_layout/settings'
    | '/_layout/shop-categories'
    | '/_layout/shops'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shops': {
      id: '/_layout/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof LayoutShopsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shop-categories': {
      id: '/_layout/shop-categories'
      path: '/shop-categories'
      fullPath: '/shop-categories'
      preLoaderRoute: typeof LayoutShopCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rightsholders': {
      id: '/_layout/rightsholders'
      path: '/rightsholders'
      fullPath: '/rightsholders'
      preLoaderRoute: typeof LayoutRightsholdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cashiers': {
      id: '/_layout/cashiers'
      path: '/cashiers'
      fullPath: '/cashiers'
      preLoaderRoute: typeof LayoutCashiersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCashiersRoute: typeof LayoutCashiersRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutRightsholdersRoute: typeof LayoutRightsholdersRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutShopCategoriesRoute: typeof LayoutShopCategoriesRoute
  LayoutShopsRoute: typeof LayoutShopsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCashiersRoute: LayoutCashiersRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutRightsholdersRoute: LayoutRightsholdersRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutShopCategoriesRoute: LayoutShopCategoriesRoute,
  LayoutShopsRoute: LayoutShopsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
